#Diksha Maharjan
##2408235


Exercise on functions
Task1


In [ ]:
def length_conversion(fromto, value):
    """
        Converts length from meters to feet or vice versa.
        parameters: fromto:string, value:float
        returns: None
    """
    try:
        if fromto == "m":
          print(value * 3.28084, "ft")
        elif fromto == "ft":
         print(value / 3.28084, "m")
    except:
        print("Invalid unit. Please enter 'm' or 'ft'")

def volume_conversion(fromto, value):
    """
        Converts volume from liters to gallons or vice versa.
        parameters: fromto:string, value:float
        returns: None
    """
    if fromto == "l":
        print(value * 0.264172, "gal")
    elif fromto == "gal":
        print(value / 0.264172, "l")
    else:
        print("Invalid unit. Please enter 'l' or 'gal'")

def weight_conversion(fromto, value):
    """
        Converts weight from kilograms to pounds or vice versa.
        parameters: fromto:string, value:float
        returns: None
    """
    if fromto == "kg":
        print(value * 2.20462, "lbs")
    elif fromto == "lbs":
        print(value / 2.20462, "kg")
    else:
        print("Invalid unit. Please enter 'kg' or 'lbs'")


con = input("Enter type of conversion (length, volume, weight): ")

if con == "length":
    fromto = input("Enter unit to convert from (m or ft): ")
    value = float(input("Enter value: "))
    length_conversion(fromto, value)

elif con == "volume":
    fromto = input("Enter unit to convert from (l or gal): ")
    value = float(input("Enter value: "))
    volume_conversion(fromto, value)

elif con == "weight":
    fromto = input("Enter unit to convert from (kg or lbs): ")
    value = float(input("Enter value: "))
    weight_conversion(fromto, value)

else:
    print("Invalid conversion type.")

Enter type of conversion (length, volume, weight): length
Enter unit to convert from (m or ft): m
Enter value: 1.54
5.0524936 ft


Task-2


In [ ]:
def calc_sum(numbers):
    """
    Calculates the sum of a list of numbers.
    Parameters: numbers (list of float)
    Returns: float: The sum of all numbers in the list.

    """
    return sum(numbers)


def calc_average(numbers):
    """
    Calculates the average (mean) of a list of numbers.
    Parameters: numbers (list of float)
    Returns: float: The arithmetic mean of all numbers in the list.
    """
    return sum(numbers) / len(numbers)


def calc_maximum(numbers):
    """
    Finds the maximum value in a list of numbers.
    Parameters: numbers (list of float)
    Returns:float: The largest number in the list.
    """
    return max(numbers)


def calc_minimum(numbers):
    """
    Finds the minimum value in a list of numbers.
    Parameters:numbers (list of float): A non-empty list of numeric values.
    Returns: float: The smallest number in the list.
    """
    return min(numbers)


def get_numbers():
    """
    Prompts the user to enter a space-separated list of numbers
    and converts them into a list of floats.
    Parameters: None
    Returns: list of float: A list of numbers entered by the user.
    error catch:
        ValueError: If the input is empty or contains non-numeric values.
    """
    raw = input("Enter numbers separated by spaces: ")
    if not raw.strip():
        raise ValueError("No numbers entered. List cannot be empty.")
    return [float(x) for x in raw.split()]


def main():
    """
    Main function that displays a menu, takes user input,
    and calls the appropriate mathematical operation function.
    Parameters: None
    Returns: None — results are printed directly to the console.
    Error: ValueError: Caught internally if input is invalid or list is empty.
    """
    print("Math Operations:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")
    print("\n")

    try:
        choice = input("Choose an operation (1/2/3/4): ").strip()

        if choice not in ("1", "2", "3", "4"):
            print("Invalid choice. Please enter 1, 2, 3, or 4.")
            return

        numbers = get_numbers()

        if choice == "1":
            print(f"Sum: {calc_sum(numbers)}")
        elif choice == "2":
            print(f"Average: {calc_average(numbers)}")
        elif choice == "3":
            print(f"Maximum: {calc_maximum(numbers)}")
        elif choice == "4":
            print(f"Minimum: {calc_minimum(numbers)}")

    except ValueError as e:
        print(f"Error: {e}")


main()

Math Operations:
1. Sum
2. Average
3. Maximum
4. Minimum


Choose an operation (1/2/3/4): 3
Enter numbers separated by spaces: 3 8
Maximum: 8.0


Exercises on List Manipulation:


In [ ]:
# 4.2 Exercise on List Manipulation


# Question 1: Extract Every Other Element
def extract_every_other(lst):
    """Returns every other element starting from the first."""
    return lst[::2]

lst1 = [1, 2, 3, 4, 5, 6]
print("Q1 - Every other element:", extract_every_other(lst1))


# Question 2: Slice a Sublist
def get_sublist(lst, start, end):
    """Returns a sublist from start to end index (inclusive)."""
    return lst[start:end + 1]

lst2 = [1, 2, 3, 4, 5, 6]
print("Q2 - Sublist (start=2, end=4):", get_sublist(lst2, 2, 4))


# Question 3: Reverse a List Using Slicing
def reverse_list(lst):
    """Returns a reversed list using slicing."""
    return lst[::-1]

lst3 = [1, 2, 3, 4, 5]
print("Q3 - Reversed list:", reverse_list(lst3))


# Question 4: Remove the First and Last Elements
def remove_first_last(lst):
    """Returns the list without the first and last elements."""
    return lst[1:-1]

lst4 = [1, 2, 3, 4, 5]
print("Q4 - Remove first & last:", remove_first_last(lst4))


# Question 5: Get the First n Elements
def get_first_n(lst, n):
    """Returns the first n elements of the list."""
    return lst[:n]

lst5 = [1, 2, 3, 4, 5]
print("Q5 - First 3 elements:", get_first_n(lst5, 3))


# Question 6: Extract Elements from the End
def get_last_n(lst, n):
    """Returns the last n elements of the list."""
    return lst[-n:]

lst6 = [1, 2, 3, 4, 5]
print("Q6 - Last 2 elements:", get_last_n(lst6, 2))


# Question 7: Extract Elements in Reverse Order
def reverse_skip(lst):
    """Returns every second element in reverse, starting from second-to-last."""
    return lst[-2::-2]

lst7 = [1, 2, 3, 4, 5, 6]
print("Q7 - Reverse skip:", reverse_skip(lst7))

Q1 - Every other element: [1, 3, 5]
Q2 - Sublist (start=2, end=4): [3, 4, 5]
Q3 - Reversed list: [5, 4, 3, 2, 1]
Q4 - Remove first & last: [2, 3, 4]
Q5 - First 3 elements: [1, 2, 3]
Q6 - Last 2 elements: [4, 5]
Q7 - Reverse skip: [5, 3, 1]


Exercises on nested list

In [ ]:

# Question 1: Flatten a Nested List
def flatten(lst):
    """Flattens a one-level nested list into a single list."""
    return [elem for sublist in lst for elem in sublist]

lst1 = [[1, 2], [3, 4], [5]]
print("Q1 - Flattened list:", flatten(lst1))


# Question 2: Accessing Nested List Elements
def access_nested_element(lst, indices):
    """Returns the element at the given indices in a nested list."""
    for i in indices:
        lst = lst[i]
    return lst

lst2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print("Q2 - Accessed element:", access_nested_element(lst2, [1, 2]))


# Question 3: Sum of All Elements in a Nested List
def sum_nested(lst):
    """Returns the sum of all elements in a nested list of any depth."""
    total = 0
    for elem in lst:
        if isinstance(elem, list):
            total += sum_nested(elem)
        else:
            total += elem
    return total

lst3 = [[1, 2], [3, [4, 5]], 6]
print("Q3 - Sum of nested list:", sum_nested(lst3))


# Question 4: Remove Specific Element from a Nested List
def remove_element(lst, elem):
    """Removes all occurrences of elem from a nested list."""
    return [[x for x in sublist if x != elem] for sublist in lst]

lst4 = [[1, 2], [3, 2], [4, 5]]
print("Q4 - After removing 2:", remove_element(lst4, 2))


# Question 5: Find the Maximum Element in a Nested List
def find_max(lst):
    """Returns the maximum element in a nested list of any depth."""
    max_val = None
    for elem in lst:
        if isinstance(elem, list):
            candidate = find_max(elem)
        else:
            candidate = elem
        if max_val is None or candidate > max_val:
            max_val = candidate
    return max_val

lst5 = [[1, 2], [3, [4, 5]], 6]
print("Q5 - Maximum element:", find_max(lst5))


# Question 6: Count Occurrences of an Element in a Nested List
def count_occurrences(lst, elem):
    """Counts how many times elem appears in a nested list."""
    count = 0
    for sublist in lst:
        count += sublist.count(elem)
    return count

lst6 = [[1, 2], [2, 3], [2, 4]]
print("Q6 - Count of 2:", count_occurrences(lst6, 2))


# Question 7: Flatten a List of Lists of Lists
def deep_flatten(lst):
    """Flattens a deeply nested list of any depth into a single list."""
    result = []
    for elem in lst:
        if isinstance(elem, list):
            result.extend(deep_flatten(elem))
        else:
            result.append(elem)
    return result

lst7 = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print("Q7 - Deep flattened list:", deep_flatten(lst7))


# Question 8: Nested List Average
def average_nested(lst):
    """Returns the average of all elements in a nested list."""
    flat = deep_flatten(lst)
    return sum(flat) / len(flat)

lst8 = [[1, 2], [3, 4], [5, 6]]
print("Q8 - Average of nested list:", average_nested(lst8))


Q1 - Flattened list: [1, 2, 3, 4, 5]
Q2 - Accessed element: 6
Q3 - Sum of nested list: 21
Q4 - After removing 2: [[1], [3], [4, 5]]
Q5 - Maximum element: 6
Q6 - Count of 2: 3
Q7 - Deep flattened list: [1, 2, 3, 4, 5, 6, 7, 8]
Q8 - Average of nested list: 3.5


exercises on numpy :pg

In [ ]:
import numpy as np

# Initialize an empty array with size 2X2.
empty_arr = np.empty((2, 2))

# Initialize an all one array with size 4X2.
ones_arr = np.ones((4, 2))

# Return a new array of given shape and type, filled with fill value.

full_arr = np.full((3, 3), 7)

# Return a new array of zeros with same shape and type as a given array.
zeros_like_arr = np.zeros_like(ones_arr)

# Return a new array of ones with same shape and type as a given array.
ones_like_arr = np.ones_like(empty_arr)

# For an existing list new_list = [1,2,3,4] convert to an numpy array.
new_list = [1, 2, 3, 4]
converted_arr = np.array(new_list)

print("Task 1 (Empty Array):\n", empty_arr)
print("\nTask 2 (4x2 Ones):\n", ones_arr)
print("\nTask 3 (3x3 Full of 7s):\n", full_arr)
print("\nTask 4 (Zeros Like Ones):\n", zeros_like_arr)
print("\nTask 5 (Ones Like Empty):\n", ones_like_arr)
print("\nTask 6 (List to Array):", converted_arr)

Task 1 (Empty Array):
 [[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]

Task 2 (4x2 Ones):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Task 3 (3x3 Full of 7s):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Task 4 (Zeros Like Ones):
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

Task 5 (Ones Like Empty):
 [[1. 1.]
 [1. 1.]]

Task 6 (List to Array): [1 2 3 4]


In [ ]:
import numpy as np

# array with values ranging from 10 to 49
print("\nTask 1: Array from 10 to 49")
array1 = np.arange(10, 50)
print(array1)
print(f"Shape: {array1.shape}")

# a 3X3 matrix with values ranging from 0 to 8
print("\nTask 2: 3x3 matrix with values 0 to 8")
array2 = np.arange(9).reshape(3, 3)
print(array2)

# a 3X3 identity matrix
print("\nTask 3: 3x3 identity matrix")
array3 = np.eye(3)
print(array3)

# a random array of size 30 and find the mean
print("\nTask 4: Random array of size 30 with mean")
array4 = np.random.random(30)
print(f"Random array: {array4}")
print(f"Mean of array: {array4.mean():.4f}")




# a zero array of size 10 and replace 5th element with 1
print("\nTask 6: Zero array with 5th element replaced by 1")
array6 = np.zeros(10)
print(f"Original zero array: {array6}")
array6[4] = 1  # 5th element (index 4)
print(f"Modified array: {array6}")

# Reverse an array arr = [1,2,0,0,4,0]
print("\nTask 7: Reverse an array")
arr = [1, 2, 0, 0, 4, 0]
array7 = np.array(arr)
print(f"Original array: {array7}")
print(f"Reversed array: {array7[::-1]}")

# a 2d array with 1 on border and 0 inside
print("\nTask 8: 2D array with 1 on border and 0 inside")
array8 = np.ones((5, 5))
array8[1:-1, 1:-1] = 0
print(array8)

# an 8X8 matrix and fill it with a checkerboard pattern
print("\nTask 9: 8x8 checkerboard pattern")
array9 = np.zeros((8, 8), dtype=int)
array9[1::2, ::2] = 1  # Fill alternate rows starting from 1 with 1 at even columns
array9[::2, 1::2] = 1  # Fill alternate rows starting from 0 with 1 at odd columns
print(array9)


Task 1: Array from 10 to 49
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Shape: (40,)

Task 2: 3x3 matrix with values 0 to 8
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Task 3: 3x3 identity matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Task 4: Random array of size 30 with mean
Random array: [0.29107342 0.07568627 0.35978185 0.25316029 0.69584592 0.61406346
 0.53952568 0.46254812 0.28941091 0.69803807 0.83084028 0.24928187
 0.59905318 0.96416076 0.93193057 0.96967652 0.50002313 0.66380968
 0.97293356 0.7426739  0.44105422 0.53436274 0.35249355 0.22252454
 0.21890567 0.0016705  0.90120254 0.99607274 0.84552301 0.56470631]
Mean of array: 0.5594

Task 5: 10x10 random array - min and max
Min value: 0.0048
Max value: 0.9852

Task 6: Zero array with 5th element replaced by 1
Original zero array: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Modified array: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Task 7: Reverse an array
Original array: [1 2 0 0 4 0]
R

In [ ]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])


print("\nGiven arrays:")
print(f"x = \n{x}")
print(f"y = \n{y}")
print(f"v = {v}")
print(f"w = {w}")

# Add the two arrays
print("Task 1: Add x and y")
result1 = x + y
print(f"x + y = \n{result1}")

# Subtract the two arrays
print("Task 2: Subtract x and y")
result2 = x - y
print(f"x - y = \n{result2}")

# Multiply the array with any integers of your choice

print("Task 3: Multiply arrays with integers")
result3_x = x * 3
result3_y = y * 5
print(f"x * 3 = \n{result3_x}")
print(f"y * 5 = \n{result3_y}")

# Find the square of each element
print("Task 4: Square of each element")
result4_x = x ** 2
result4_y = y ** 2
result4_v = v ** 2
print(f"x squared = \n{result4_x}")
print(f"y squared = \n{result4_y}")
print(f"v squared = {result4_v}")

# Find dot products
print("Task 5: Dot products")

# v and w dot product
dot_vw = np.dot(v, w)
print(f"v · w = {dot_vw}")

# x and v dot product
dot_xv = np.dot(x, v)
print(f"x · v = {dot_xv}")

# x and y dot product
dot_xy = np.dot(x, y)
print(f"x · y = \n{dot_xy}")

# Concatenate x and y along row; v and w along column
print("Task 6: Concatenation")

# Concatenate x and y along row (vertical stack)
concat_xy_row = np.concatenate((x, y), axis=0)  # or np.vstack((x, y))
print(f"x and y concatenated along row (axis=0):\n{concat_xy_row}")

# Concatenate v and w along column (need to reshape first for column concatenation)
v_reshaped = v.reshape(-1, 1)
w_reshaped = w.reshape(-1, 1)
concat_vw_col = np.concatenate((v_reshaped, w_reshaped), axis=1)
print(f"\nv and w concatenated along column (axis=1):\n{concat_vw_col}")
print(f"v reshaped to column:\n{v_reshaped}")
print(f"w reshaped to column:\n{w_reshaped}")

# Alternative for v and w along column using column_stack
concat_vw_col_alt = np.column_stack((v, w))
print(f"\nAlternative using column_stack:\n{concat_vw_col_alt}")

# Concatenate x and v (will cause error)
print("Task 7: Attempt to concatenate x and v")
print("x shape:", x.shape)
print("v shape:", v.shape)

try:
    concat_xv = np.concatenate((x, v))
    print(f"x and v concatenated:\n{concat_xv}")
except Exception as e:
    print(f"ERROR: {e}")
    print("\nExplanation:")
    print("x has shape (2, 2) - a 2D array with 2 rows and 2 columns")
    print("v has shape (2,) - a 1D array with 2 elements")
    print("To concatenate, arrays must have the same number of dimensions")
    print("and compatible shapes along the concatenation axis.")
    print("\nSolutions to fix this:")
    print("1. Reshape v to match x's dimensions: v.reshape(2, 1) or v.reshape(1, 2)")
    print("2. Use np.vstack((x, v)) - but v would need to be reshaped to (1, 2)")
    print("3. Flatten x to 1D: x.flatten() and then concatenate with v")

    # Show possible solutions
    print("\nPossible ways to concatenate:")
    # Reshape v to 2D column vector
    v_col = v.reshape(2, 1)
    print(f"v reshaped to (2,1):\n{v_col}")
    print(f"Cannot concatenate with x (2,2) along axis=1 due to shape mismatch")

    # Reshape v to 2D row vector
    v_row = v.reshape(1, 2)
    concat_x_vrow = np.concatenate((x, v_row), axis=0)
    print(f"\nv reshaped to (1,2):\n{v_row}")
    print(f"x and v_row concatenated along axis=0:\n{concat_x_vrow}")

    # Flatten x
    x_flat = x.flatten()
    concat_flat = np.concatenate((x_flat, v))
    print(f"\nx flattened: {x_flat}")
    print(f"x_flat and v concatenated: {concat_flat}")


Given arrays:
x = 
[[1 2]
 [3 5]]
y = 
[[5 6]
 [7 8]]
v = [ 9 10]
w = [11 12]
Task 1: Add x and y
x + y = 
[[ 6  8]
 [10 13]]
Task 2: Subtract x and y
x - y = 
[[-4 -4]
 [-4 -3]]
Task 3: Multiply arrays with integers
x * 3 = 
[[ 3  6]
 [ 9 15]]
y * 5 = 
[[25 30]
 [35 40]]
Task 4: Square of each element
x squared = 
[[ 1  4]
 [ 9 25]]
y squared = 
[[25 36]
 [49 64]]
v squared = [ 81 100]
Task 5: Dot products
v · w = 219
x · v = [29 77]
x · y = 
[[19 22]
 [50 58]]
Task 6: Concatenation
x and y concatenated along row (axis=0):
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

v and w concatenated along column (axis=1):
[[ 9 11]
 [10 12]]
v reshaped to column:
[[ 9]
 [10]]
w reshaped to column:
[[11]
 [12]]

Alternative using column_stack:
[[ 9 11]
 [10 12]]
Task 7: Attempt to concatenate x and v
x shape: (2, 2)
v shape: (2,)
ERROR: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Explanation:
x has shape (2, 2)

In [5]:
import numpy as np
import time

# 1. Prepare the Data (1 million numbers)
size = 1000000
list_a = list(range(size))
list_b = list(range(size))

array_a = np.array(list_a)
array_b = np.array(list_b)

print(f"Testing with {size} elements\n")

# ELEMENT-WISE ADDITION
# Python List
start = time.time()
result_list = [a + b for a, b in zip(list_a, list_b)]
python_time = time.time() - start
print(f"Addition (Python): {python_time:.5f}s")

# NumPy Array
start = time.time()
result_array = array_a + array_b
numpy_time = time.time() - start
print(f"Addition (NumPy):  {numpy_time:.5f}s\n\n")


# DOT PRODUCT
# Python List
start = time.time()
dot_product = sum(a * b for a, b in zip(list_a, list_b))
python_time = time.time() - start
print(f"Dot Product (Python): {python_time:.5f}s")

# NumPy Array
start = time.time()
dot_product_np = np.dot(array_a, array_b)
numpy_time = time.time() - start
print(f"Dot Product (NumPy):  {numpy_time:.5f}s\n\n")

# MATRIX MULTIPLICATION (100x100 for safety)
# Note: Using 100x100 because 1000x1000 in plain Python can take minutes!
m_size = 100
m_list = [[1 for _ in range(m_size)] for _ in range(m_size)]
m_array = np.array(m_list)

# Python List (Three nested loops)
start = time.time()
res = [[0 for _ in range(m_size)] for _ in range(m_size)]
for i in range(m_size):
    for j in range(m_size):
        for k in range(m_size):
            res[i][j] += m_list[i][k] * m_list[k][j]
python_time = time.time() - start
print(f"Matrix Mult (Python): {python_time:.5f}s")

# NumPy Array
start = time.time()
res_np = np.matmul(m_array, m_array)
numpy_time = time.time() - start
print(f"Matrix Mult (NumPy):  {numpy_time:.5f}s")

Testing with 1000000 elements

Addition (Python): 0.07849s
Addition (NumPy):  0.00198s


Dot Product (Python): 0.08360s
Dot Product (NumPy):  0.00176s


Matrix Mult (Python): 0.24088s
Matrix Mult (NumPy):  0.00140s
